kind: 'floom/pipeline/1.2'

pipeline:
  name: pipeline-idm-docs1

  model:
    - package: floom/model/connector/openai
      model: gpt-3.5-turbo
      apiKey: sk-1234567890abcdefg=

  prompt:
    template:
      package: floom/prompt/template/default

  response:
    format:
      - package: floom/response/formatter
        type: text
        language: en
        max-sentences: 20
        max-characters: 10000